x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./superset:/app/superset
  - ./docker/superset_config.py:/app/pythonpath/superset_config.py


services:
  postgres:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - 5001:5432
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      - ./postgres/superset_init.sql:/docker-entrypoint-initdb.d/superset_init.sql
    networks:
      - my-network


  airflow:
    container_name: airflow_container
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/api-request
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1001'
    depends_on:
      - postgres
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    platform: linux/amd64
    volumes:
      - ./dbt/weather_project:/usr/app
      - ./dbt:/root/.dbt
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    working_dir: /usr/app
    depends_on:
      - postgres
    networks:
      - my-network
    command: run

  superset-init:
    platform: linux/amd64
    image: apache/superset:3.0.0-py310
    user: root
    environment:
      # Superset 必須要有 Secret Key 才能啟動
      SUPERSET_SECRET_KEY: "my_super_secret_key_12345"
      # 直接連線到你的 Postgres
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://weather_user:postgres@postgres:5432/weather_db"
    # 我們不依賴外部腳本，直接用標準指令：更新資料庫 -> 建立管理員 -> 初始化
    command: >
      bash -c "superset db upgrade &&
               superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
               superset init"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - my-network

  superset:
    platform: linux/amd64
    image: apache/superset:3.0.0-py310
    user: root
    environment:
      SUPERSET_SECRET_KEY: "my_super_secret_key_12345"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://weather_user:postgres@postgres:5432/weather_db"
    # 啟動正式的 Web 伺服器 (gunicorn)
    command: >
      bash -c "gunicorn -w 2 --timeout 120 -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 'superset.app:create_app()'"
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      superset-init:
        condition: service_completed_successfully
    networks:
      - my-network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  redis:
    external: false